### ISSUE TITLE
problem with build lib

### ISSUE THREAD

**Issue by Gambler19** [ahtabrizi/gstnvstabilize#1]
when we are run to make in cd gst-stabilize, after the move source code we have a mistake
gstnvstabilize.h:41:10: fatal error: NVX/nvx.h: No such file or directory
 #include <NVX/nvx.h>
Could you tell me, what i need to do, please!
Thank you

**Comment by Gambler19** [comment]
I can solve this problem with install visionworks on my Jetson Tx2, but then i get other mistake with using plugin nvstabilize:
my pipeline is: gst-launch-1.0 autovideosrc ! videoconvert ! nvstabilize queue-size=6 ! videoconvert ! autovideosink
my error is: ERROR:gstnvstabilize.cpp:2511:GstCaps* gst_nvstabilize_fixate_caps(GstBaseTransform*, GstPadDirection, GstCaps*, GstCaps*): code should not be reached
Aborted (core dumped)
Could someone help ?

**Comment by ahtabrizi** [comment]
I think you should define the output formats of videoconvert. Check out pipeline examples in readme.
